# permissions for end users to edit cas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ca-editor-role
rules:
- apiGroups:
  - fabric.hyperledger.org
  resources:
  - cas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fabric.hyperledger.org
  resources:
  - cas/status
  verbs:
  - get
