# permissions for end users to view orderers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orderer-viewer-role
rules:
- apiGroups:
  - fabric.hyperledger.org
  resources:
  - orderers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fabric.hyperledger.org
  resources:
  - orderers/status
  verbs:
  - get
