# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/fabric.hyperledger.org_cas.yaml
- bases/fabric.hyperledger.org_peers.yaml
- bases/fabric.hyperledger.org_orderers.yaml
- bases/fabric.hyperledger.org_chaincodes.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_cas.yaml
#- patches/webhook_in_peers.yaml
#- patches/webhook_in_orderers.yaml
#- patches/webhook_in_chaincodes.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_cas.yaml
#- patches/cainjection_in_peers.yaml
#- patches/cainjection_in_orderers.yaml
#- patches/cainjection_in_chaincodes.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
